"""Tests for loopwright/scripts/index.py, through its command line.

Every test builds a throwaway tasks directory with invented tasks and checks
the generated INDEX.md and the exit code.
"""

import subprocess
import sys
from pathlib import Path

import pytest

SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "index.py"


def run_index(tasks_dir, *args):
    return subprocess.run(
        [sys.executable, str(SCRIPT), str(tasks_dir), *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
    )


def make_task(
    tasks_dir,
    folder,
    task_id,
    slug="job",
    title=None,
    body="Body text.\n",
    **fields,
):
    """Write tasks/<folder>/<id>-<slug>.md. Fields override the valid defaults;
    pass a field as None to leave it out."""
    meta = {"type": "task", "mode": "auto", "status": "open"}
    if folder == "done":
        meta["status"] = "done"
    meta.update(fields)
    lines = ["---"]
    lines += [f"{k}: {v}" for k, v in meta.items() if v is not None]
    lines.append("---")
    heading = "" if title is False else f"# {task_id}. {title or 'Task ' + str(task_id)}\n"
    path = Path(tasks_dir) / folder / f"{task_id:03d}-{slug}.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n" + heading + body, encoding="utf-8")
    return path


def read_index(tasks_dir):
    return (Path(tasks_dir) / "INDEX.md").read_text(encoding="utf-8")


def table_rows(index_text):
    return [
        line
        for line in index_text.splitlines()
        if line.startswith("|") and not line.startswith(("| id", "|--", "| --"))
    ]


def test_index_lists_open_tasks_sorted_by_id_with_all_columns(tmp_path):
    # Created out of order, in different folders: rows must follow the id.
    make_task(
        tmp_path, "features", 12, "second", title="Second job", priority="low",
        depends="[3]",
    )
    make_task(
        tmp_path, "bugs", 3, "first", title="First job", type="bug", mode="human",
        priority="high",
    )
    make_task(
        tmp_path, "unrefined", 20, "third", title="Third job", status="in-progress",
        depends="[3, 12]",
    )

    result = run_index(tmp_path)

    assert result.returncode == 0, result.stderr
    d = tmp_path.name  # paths in the index start with the tasks directory's name
    assert table_rows(read_index(tmp_path)) == [
        f"| 3 | bug | human | open | high | - | First job | {d}/bugs/003-first.md |",
        f"| 12 | task | auto | open | low | 3 | Second job | {d}/features/012-second.md |",
        f"| 20 | task | auto | in-progress | - | 3, 12 | Third job | {d}/unrefined/020-third.md |",
    ]


def test_index_has_header_columns_and_legend(tmp_path):
    make_task(tmp_path, "bugs", 1, type="bug")

    run_index(tmp_path)
    lines = read_index(tmp_path).splitlines()

    assert "| id | type | mode | status | priority | depends | title | path |" in lines
    assert "Generated by `loopwright/scripts/index.py`. Do not edit by hand." in lines
    assert [line for line in lines if line.startswith("- ")] == [
        "- type: bug | task | story",
        "- mode: auto (no decisions left, agents can do it) | "
        "human (needs a decision or a step only the user can do)",
        "- status: open | in-progress | done",
        "- priority: high | medium | low | backlog, or - when not set",
        "- depends: ids of tasks that must be done first, or - when none",
        f"- path: relative to the directory above `{tmp_path.name}/`",
    ]


def test_done_tasks_are_one_line_of_ids_and_not_rows(tmp_path):
    make_task(tmp_path, "done", 10)
    make_task(tmp_path, "done", 2)
    make_task(tmp_path, "bugs", 5, type="bug")

    run_index(tmp_path)
    text = read_index(tmp_path)

    assert "\n2, 10\n" in text
    assert len(table_rows(text)) == 1


def test_no_open_tasks_still_writes_a_valid_index(tmp_path):
    make_task(tmp_path, "done", 1)

    result = run_index(tmp_path)

    assert result.returncode == 0
    assert table_rows(read_index(tmp_path)) == []
    assert "\n1\n" in read_index(tmp_path)


# guard: /loopwright:init relies on an empty tasks dir giving a valid, empty index;
# catches changing the empty Done line to blank or '-'.
def test_empty_tasks_dir_writes_an_index(tmp_path):
    result = run_index(tmp_path)

    assert result.returncode == 0
    assert table_rows(read_index(tmp_path)) == []
    assert "\n## Done\n\nnone\n" in read_index(tmp_path)


def test_running_twice_gives_the_same_index(tmp_path):
    # INDEX.md sits in the scanned tree; it must not be read as a task.
    make_task(tmp_path, "features", 4)
    run_index(tmp_path)
    first = read_index(tmp_path)

    result = run_index(tmp_path)

    assert result.returncode == 0
    assert read_index(tmp_path) == first


def test_files_not_named_like_tasks_are_ignored(tmp_path):
    make_task(tmp_path, "bugs", 1, type="bug")
    (tmp_path / "NOTES.md").write_text("no front matter here\n", encoding="utf-8")
    (tmp_path / "bugs" / "readme.md").write_text("nor here\n", encoding="utf-8")
    (tmp_path / "bugs" / "07-short-id.md").write_text("nor here\n", encoding="utf-8")

    result = run_index(tmp_path)

    assert result.returncode == 0, result.stderr
    assert len(table_rows(read_index(tmp_path))) == 1


def test_depends_and_parent_are_accepted(tmp_path):
    make_task(tmp_path, "features", 1, type="story")
    make_task(tmp_path, "features", 2, parent=1)
    make_task(tmp_path, "features", 3, parent=1, depends="[2]")
    make_task(tmp_path, "features", 4, depends="[2, 3]")

    result = run_index(tmp_path)

    assert result.returncode == 0, result.stderr
    assert len(table_rows(read_index(tmp_path))) == 4


def test_title_comes_from_the_heading_without_its_number(tmp_path):
    make_task(tmp_path, "bugs", 8, type="bug", title="Fix: the `thing` breaks, again")

    run_index(tmp_path)

    assert "| Fix: the `thing` breaks, again |" in read_index(tmp_path)


@pytest.mark.parametrize(
    "existing, expected",
    [
        ([], "001"),
        ([1, 2, 3], "004"),
        ([5, 41], "042"),  # gaps: the next id follows the highest, never fills one
    ],
)
def test_next_id_follows_the_highest_id(tmp_path, existing, expected):
    for task_id in existing:
        make_task(tmp_path, "features", task_id)

    result = run_index(tmp_path, "--next-id")

    assert result.returncode == 0, result.stderr
    assert result.stdout.strip() == expected


def test_next_id_counts_done_tasks(tmp_path):
    make_task(tmp_path, "features", 3)
    make_task(tmp_path, "done", 9)

    assert run_index(tmp_path, "--next-id").stdout.strip() == "010"


# guard: catches an over-fix where the --next-id path also writes INDEX.md.
def test_next_id_does_not_write_the_index(tmp_path):
    make_task(tmp_path, "features", 3)

    run_index(tmp_path, "--next-id")

    assert not (tmp_path / "INDEX.md").exists()


@pytest.mark.parametrize("field", ["type", "mode", "status"])
def test_missing_required_tag_fails_naming_file_and_tag(tmp_path, field):
    path = make_task(tmp_path, "features", 1, **{field: None})

    result = run_index(tmp_path)

    assert result.returncode == 1
    assert path.name in result.stderr
    assert field in result.stderr
    assert not (tmp_path / "INDEX.md").exists()


@pytest.mark.parametrize(
    "field, value",
    [
        ("type", "epic"),
        ("mode", "robot"),
        ("status", "blocked"),
        ("priority", "urgent"),
        ("depends", "2"),  # a list is required
        ("depends", "[two]"),
        ("parent", "[1]"),
        ("colour", "red"),  # unknown key: usually a typo
    ],
)
def test_invalid_tag_value_fails(tmp_path, field, value):
    path = make_task(tmp_path, "features", 1, **{field: value})

    result = run_index(tmp_path)

    assert result.returncode == 1
    assert path.name in result.stderr
    assert field in result.stderr


@pytest.mark.parametrize("field", ["depends", "parent"])
def test_reference_to_unknown_id_fails(tmp_path, field):
    value = "[99]" if field == "depends" else "99"
    make_task(tmp_path, "features", 1, **{field: value})

    result = run_index(tmp_path)

    assert result.returncode == 1
    assert "99" in result.stderr


def test_duplicate_id_fails_naming_both_files(tmp_path):
    make_task(tmp_path, "bugs", 7, "alpha", type="bug")
    make_task(tmp_path, "features", 7, "beta")

    result = run_index(tmp_path)

    assert result.returncode == 1
    assert "007-alpha.md" in result.stderr
    assert "007-beta.md" in result.stderr
    assert not (tmp_path / "INDEX.md").exists()


@pytest.mark.parametrize(
    "folder, status",
    [
        ("bugs", "done"),
        ("features", "done"),
        ("unrefined", "done"),
        ("done", "open"),
        ("done", "in-progress"),
    ],
)
def test_folder_must_match_status(tmp_path, folder, status):
    path = make_task(tmp_path, folder, 1, status=status)

    result = run_index(tmp_path)

    assert result.returncode == 1
    assert path.name in result.stderr
    assert "done" in result.stderr


@pytest.mark.parametrize("status", ["open", "in-progress"])
@pytest.mark.parametrize("folder", ["bugs", "features", "unrefined"])
def test_open_and_in_progress_are_valid_in_any_non_done_folder(tmp_path, folder, status):
    make_task(tmp_path, folder, 1, status=status)

    assert run_index(tmp_path).returncode == 0


def test_file_without_front_matter_fails(tmp_path):
    (tmp_path / "bugs").mkdir()
    path = tmp_path / "bugs" / "001-plain.md"
    path.write_text("# 1. Plain\nNo tags.\n", encoding="utf-8")

    result = run_index(tmp_path)

    assert result.returncode == 1
    assert path.name in result.stderr


def test_unclosed_front_matter_fails(tmp_path):
    (tmp_path / "bugs").mkdir()
    path = tmp_path / "bugs" / "001-open.md"
    path.write_text("---\ntype: bug\nmode: auto\nstatus: open\n# 1. Open\n", encoding="utf-8")

    result = run_index(tmp_path)

    assert result.returncode == 1
    assert path.name in result.stderr


def test_missing_title_heading_fails(tmp_path):
    path = make_task(tmp_path, "features", 1, title=False)

    result = run_index(tmp_path)

    assert result.returncode == 1
    assert path.name in result.stderr


def test_all_problems_are_reported_in_one_run(tmp_path):
    make_task(tmp_path, "features", 1, type="epic")
    make_task(tmp_path, "features", 2, mode=None)

    result = run_index(tmp_path)

    assert result.returncode == 1
    assert "001-job.md" in result.stderr
    assert "002-job.md" in result.stderr


def test_missing_tasks_dir_fails(tmp_path):
    result = run_index(tmp_path / "nope")

    assert result.returncode != 0
    assert "nope" in result.stderr


@pytest.mark.parametrize("folder", [".", "archive", "bugs/nested"])
def test_task_file_outside_the_four_folders_fails(tmp_path, folder):
    path = make_task(tmp_path, folder, 1)

    result = run_index(tmp_path)

    assert result.returncode == 1
    assert path.name in result.stderr
    assert "folder" in result.stderr


def test_typo_in_one_file_does_not_hide_its_id_from_references(tmp_path):
    make_task(tmp_path, "features", 1, type="epic")  # invalid, but id 1 exists
    make_task(tmp_path, "features", 2, depends="[1]")

    result = run_index(tmp_path)

    assert result.returncode == 1
    assert "no task with id" not in result.stderr


def test_duplicate_id_is_reported_even_if_the_second_copy_is_invalid(tmp_path):
    make_task(tmp_path, "bugs", 7, "alpha", type="bug")
    make_task(tmp_path, "features", 7, "beta", mode=None)

    result = run_index(tmp_path)

    assert result.returncode == 1
    assert "duplicate id 7" in result.stderr
